'use client';

import { useState } from 'react';
import Link from 'next/link';
import Footer from '../../components/Footer';

export default function DepreciationCalculator() {
  const [assetCost, setAssetCost] = useState('');
  const [salvageValue, setSalvageValue] = useState('');
  const [usefulLife, setUsefulLife] = useState('');
  const [method, setMethod] = useState<'straight-line' | 'declining-balance'>('straight-line');
  const [rate, setRate] = useState('20');
  const [schedule, setSchedule] = useState<Array<{year: number; depreciation: number; accumulated: number; bookValue: number}>>([]);

  const calculate = () => {
    const cost = parseFloat(assetCost);
    const salvage = parseFloat(salvageValue) || 0;
    const life = parseInt(usefulLife);

    if (isNaN(cost) || isNaN(life) || cost <= 0 || life <= 0) {
      alert('Please enter valid values');
      return;
    }

    const newSchedule: Array<{year: number; depreciation: number; accumulated: number; bookValue: number}> = [];
    
    if (method === 'straight-line') {
      const annualDepreciation = (cost - salvage) / life;
      let accumulated = 0;
      
      for (let year = 1; year <= life; year++) {
        accumulated += annualDepreciation;
        newSchedule.push({
          year,
          depreciation: annualDepreciation,
          accumulated,
          bookValue: cost - accumulated,
        });
      }
    } else {
      // Declining balance
      const depRate = parseFloat(rate) / 100;
      let bookValue = cost;
      let accumulated = 0;
      
      for (let year = 1; year <= life; year++) {
        const depreciation = bookValue * depRate;
        accumulated += depreciation;
        bookValue -= depreciation;
        
        newSchedule.push({
          year,
          depreciation,
          accumulated,
          bookValue: Math.max(bookValue, salvage),
        });
        
        if (bookValue <= salvage) break;
      }
    }
    
    setSchedule(newSchedule);
  };

  const printSchedule = () => {
    const printWindow = window.open('', '', 'height=800,width=1000');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>Depreciation Schedule</title>
            <style>
              body { font-family: Arial, sans-serif; padding: 40px; }
              h1 { color: #eab308; }
              table { width: 100%; border-collapse: collapse; margin: 20px 0; }
              th, td { padding: 12px; text-align: right; border: 1px solid #ddd; }
              th { background-color: #fef3c7; }
              .info { margin: 20px 0; }
            </style>
          </head>
          <body>
            <h1>Depreciation Schedule</h1>
            <div class="info">
              <p><strong>Asset Cost:</strong> ₹${parseFloat(assetCost).toFixed(2)}</p>
              <p><strong>Salvage Value:</strong> ₹${parseFloat(salvageValue || '0').toFixed(2)}</p>
              <p><strong>Useful Life:</strong> ${usefulLife} years</p>
              <p><strong>Method:</strong> ${method === 'straight-line' ? 'Straight Line' : 'Declining Balance'}</p>
            </div>
            <table>
              <thead>
                <tr>
                  <th>Year</th>
                  <th>Depreciation</th>
                  <th>Accumulated</th>
                  <th>Book Value</th>
                </tr>
              </thead>
              <tbody>
                ${schedule.map(row => `
                  <tr>
                    <td>${row.year}</td>
                    <td>₹${row.depreciation.toFixed(2)}</td>
                    <td>₹${row.accumulated.toFixed(2)}</td>
                    <td>₹${row.bookValue.toFixed(2)}</td>
                  </tr>
                `).join('')}
              </tbody>
            </table>
            <p style="margin-top: 40px; color: #666;">Generated by InvoSync - ${new Date().toLocaleString()}</p>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-gray-100 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
      <header className="sticky top-0 z-50 w-full border-b border-gray-200 bg-white/80 backdrop-blur-sm dark:border-gray-800 dark:bg-gray-900/80">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex h-16 items-center justify-between">
            <Link href="/" className="flex items-center gap-2">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-br from-blue-600 to-indigo-600">
                <span className="text-xl font-bold text-white">I</span>
              </div>
              <span className="text-xl font-bold text-gray-900 dark:text-white">InvoSync</span>
            </Link>
            <Link href="/tools" className="text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
              ← Back to Tools
            </Link>
          </div>
        </div>
      </header>

      <section className="container mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="mx-auto max-w-6xl">
          <div className="inline-flex h-20 w-20 items-center justify-center rounded-2xl bg-gradient-to-br from-yellow-500 to-yellow-600 text-4xl shadow-lg mb-6">
            📉
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl dark:text-white mb-4">
            Depreciation Calculator
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300 mb-8">
            Calculate asset depreciation using various methods.
          </p>

          <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
            <div className="lg:col-span-1 rounded-2xl bg-white p-6 shadow-lg dark:bg-gray-800 h-fit">
              <h2 className="text-xl font-bold text-gray-900 dark:text-white mb-4">Asset Details</h2>
              
              <div className="space-y-4">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Asset Cost (₹)
                  </label>
                  <input
                    type="number"
                    value={assetCost}
                    onChange={(e) => setAssetCost(e.target.value)}
                    placeholder="100000"
                    className="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-gray-900 focus:border-yellow-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Salvage Value (₹)
                  </label>
                  <input
                    type="number"
                    value={salvageValue}
                    onChange={(e) => setSalvageValue(e.target.value)}
                    placeholder="10000"
                    className="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-gray-900 focus:border-yellow-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Useful Life (years)
                  </label>
                  <input
                    type="number"
                    value={usefulLife}
                    onChange={(e) => setUsefulLife(e.target.value)}
                    placeholder="5"
                    className="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-gray-900 focus:border-yellow-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Method
                  </label>
                  <select
                    value={method}
                    onChange={(e) => setMethod(e.target.value as any)}
                    className="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-gray-900 focus:border-yellow-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                  >
                    <option value="straight-line">Straight Line</option>
                    <option value="declining-balance">Declining Balance</option>
                  </select>
                </div>

                {method === 'declining-balance' && (
                  <div>
                    <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Depreciation Rate (%)
                    </label>
                    <input
                      type="number"
                      value={rate}
                      onChange={(e) => setRate(e.target.value)}
                      className="w-full rounded-lg border border-gray-300 bg-white px-4 py-2.5 text-gray-900 focus:border-yellow-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                    />
                  </div>
                )}

                <button
                  onClick={calculate}
                  className="w-full rounded-lg bg-gradient-to-r from-yellow-500 to-yellow-600 px-6 py-3 font-semibold text-white shadow-lg transition-all hover:from-yellow-600 hover:to-yellow-700"
                >
                  Calculate
                </button>
              </div>
            </div>

            <div className="lg:col-span-2 rounded-2xl bg-white p-6 shadow-lg dark:bg-gray-800">
              <div className="flex justify-between items-center mb-6">
                <h2 className="text-xl font-bold text-gray-900 dark:text-white">Depreciation Schedule</h2>
                {schedule.length > 0 && (
                  <button
                    onClick={printSchedule}
                    className="px-4 py-2 rounded-lg bg-yellow-500 text-white font-medium hover:bg-yellow-600 transition-colors"
                  >
                    🖨️ Print
                  </button>
                )}
              </div>

              {schedule.length > 0 ? (
                <div className="overflow-x-auto">
                  <table className="w-full">
                    <thead>
                      <tr className="border-b-2 border-yellow-500">
                        <th className="text-left py-3 px-4 font-semibold text-gray-900 dark:text-white">Year</th>
                        <th className="text-right py-3 px-4 font-semibold text-gray-900 dark:text-white">Depreciation</th>
                        <th className="text-right py-3 px-4 font-semibold text-gray-900 dark:text-white">Accumulated</th>
                        <th className="text-right py-3 px-4 font-semibold text-gray-900 dark:text-white">Book Value</th>
                      </tr>
                    </thead>
                    <tbody>
                      {schedule.map((row) => (
                        <tr key={row.year} className="border-b border-gray-200 dark:border-gray-700">
                          <td className="py-3 px-4 text-gray-700 dark:text-gray-300">{row.year}</td>
                          <td className="text-right py-3 px-4 text-gray-700 dark:text-gray-300">₹{row.depreciation.toFixed(2)}</td>
                          <td className="text-right py-3 px-4 text-gray-700 dark:text-gray-300">₹{row.accumulated.toFixed(2)}</td>
                          <td className="text-right py-3 px-4 font-semibold text-gray-900 dark:text-white">₹{row.bookValue.toFixed(2)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              ) : (
                <div className="text-center py-12">
                  <div className="text-6xl mb-4">📉</div>
                  <p className="text-gray-500 dark:text-gray-400">
                    Enter asset details and click Calculate
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
