'use client';

import { useState } from 'react';
import Link from 'next/link';
import Footer from '../../components/Footer';

export default function GSTCalculator() {
  const [amount, setAmount] = useState('');
  const [gstRate, setGstRate] = useState('18');
  const [calculationType, setCalculationType] = useState<'exclusive' | 'inclusive'>('exclusive');
  const [result, setResult] = useState<{
    originalAmount: number;
    gstAmount: number;
    cgst: number;
    sgst: number;
    totalAmount: number;
  } | null>(null);

  const calculateGST = () => {
    const amt = parseFloat(amount);
    const rate = parseFloat(gstRate);

    if (isNaN(amt) || isNaN(rate) || amt <= 0) {
      alert('Please enter a valid amount greater than 0');
      return;
    }

    let originalAmount: number;
    let gstAmount: number;
    let totalAmount: number;

    if (calculationType === 'exclusive') {
      originalAmount = amt;
      gstAmount = (amt * rate) / 100;
      totalAmount = amt + gstAmount;
    } else {
      totalAmount = amt;
      originalAmount = (amt * 100) / (100 + rate);
      gstAmount = amt - originalAmount;
    }

    const cgst = gstAmount / 2;
    const sgst = gstAmount / 2;

    setResult({
      originalAmount: parseFloat(originalAmount.toFixed(2)),
      gstAmount: parseFloat(gstAmount.toFixed(2)),
      cgst: parseFloat(cgst.toFixed(2)),
      sgst: parseFloat(sgst.toFixed(2)),
      totalAmount: parseFloat(totalAmount.toFixed(2)),
    });
  };

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text);
    alert('Copied to clipboard!');
  };

  const printResults = () => {
    if (!result) return;
    const printWindow = window.open('', '', 'height=600,width=800');
    if (printWindow) {
      printWindow.document.write(`
        <html>
          <head>
            <title>GST Calculation - InvoSync</title>
            <style>
              body { font-family: Arial, sans-serif; padding: 40px; }
              h1 { color: #2563eb; }
              table { width: 100%; border-collapse: collapse; margin-top: 20px; }
              th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
              th { background-color: #f3f4f6; }
              .total { font-weight: bold; font-size: 1.2em; background-color: #dbeafe; }
            </style>
          </head>
          <body>
            <h1>GST Calculation Report</h1>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
            <p><strong>Calculation Type:</strong> GST ${calculationType === 'exclusive' ? 'Exclusive' : 'Inclusive'}</p>
            <p><strong>GST Rate:</strong> ${gstRate}%</p>
            <table>
              <tr><th>Description</th><th>Amount (₹)</th></tr>
              <tr><td>Original Amount</td><td>${result.originalAmount}</td></tr>
              <tr><td>GST Amount (${gstRate}%)</td><td>${result.gstAmount}</td></tr>
              <tr><td>CGST (${parseFloat(gstRate) / 2}%)</td><td>${result.cgst}</td></tr>
              <tr><td>SGST (${parseFloat(gstRate) / 2}%)</td><td>${result.sgst}</td></tr>
              <tr class="total"><td>Total Amount</td><td>₹${result.totalAmount}</td></tr>
            </table>
            <p style="margin-top: 40px; color: #666; font-size: 0.9em;">Generated by InvoSync - Business Management Software</p>
          </body>
        </html>
      `);
      printWindow.document.close();
      printWindow.print();
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-gray-100 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
      <header className="sticky top-0 z-50 w-full border-b border-gray-200 bg-white/80 backdrop-blur-sm dark:border-gray-800 dark:bg-gray-900/80">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex h-16 items-center justify-between">
            <Link href="/" className="flex items-center gap-2">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-br from-blue-600 to-indigo-600">
                <span className="text-xl font-bold text-white">I</span>
              </div>
              <span className="text-xl font-bold text-gray-900 dark:text-white">InvoSync</span>
            </Link>
            <Link href="/tools" className="text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
              ← Back to Tools
            </Link>
          </div>
        </div>
      </header>

      <section className="container mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="mx-auto max-w-4xl">
          <div className="inline-flex h-20 w-20 items-center justify-center rounded-2xl bg-gradient-to-br from-green-500 to-green-600 text-4xl shadow-lg mb-6">
            🧮
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl dark:text-white mb-4">
            GST Calculator
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300 mb-8">
            Calculate GST amounts quickly and accurately for your business transactions.
          </p>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Calculator Form */}
            <div className="rounded-2xl bg-white p-8 shadow-lg dark:bg-gray-800">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6">Calculate GST</h2>

              <div className="space-y-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Calculation Type
                  </label>
                  <div className="grid grid-cols-2 gap-4">
                    <button
                      onClick={() => setCalculationType('exclusive')}
                      className={`px-4 py-3 rounded-lg font-medium transition-all ${
                        calculationType === 'exclusive'
                          ? 'bg-gradient-to-r from-green-500 to-green-600 text-white shadow-lg'
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-300'
                      }`}
                    >
                      GST Exclusive
                    </button>
                    <button
                      onClick={() => setCalculationType('inclusive')}
                      className={`px-4 py-3 rounded-lg font-medium transition-all ${
                        calculationType === 'inclusive'
                          ? 'bg-gradient-to-r from-green-500 to-green-600 text-white shadow-lg'
                          : 'bg-gray-100 text-gray-700 hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-300'
                      }`}
                    >
                      GST Inclusive
                    </button>
                  </div>
                </div>

                <div>
                  <label htmlFor="amount" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Amount (₹)
                  </label>
                  <input
                    type="number"
                    id="amount"
                    value={amount}
                    onChange={(e) => setAmount(e.target.value)}
                    className="w-full rounded-lg border border-gray-300 bg-white px-4 py-3 text-gray-900 focus:border-green-500 focus:outline-none focus:ring-2 focus:ring-green-500/20 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                    placeholder="Enter amount"
                  />
                </div>

                <div>
                  <label htmlFor="gstRate" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    GST Rate (%)
                  </label>
                  <select
                    id="gstRate"
                    value={gstRate}
                    onChange={(e) => setGstRate(e.target.value)}
                    className="w-full rounded-lg border border-gray-300 bg-white px-4 py-3 text-gray-900 focus:border-green-500 focus:outline-none focus:ring-2 focus:ring-green-500/20 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                  >
                    <option value="0">0%</option>
                    <option value="0.25">0.25%</option>
                    <option value="3">3%</option>
                    <option value="5">5%</option>
                    <option value="12">12%</option>
                    <option value="18">18%</option>
                    <option value="28">28%</option>
                  </select>
                </div>

                <button
                  onClick={calculateGST}
                  className="w-full rounded-lg bg-gradient-to-r from-green-500 to-green-600 px-6 py-3 font-semibold text-white shadow-lg transition-all hover:from-green-600 hover:to-green-700"
                >
                  Calculate
                </button>
              </div>
            </div>

            {/* Results */}
            <div className="rounded-2xl bg-white p-8 shadow-lg dark:bg-gray-800">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6">Results</h2>

              {result ? (
                <div className="space-y-4">
                  <div className="flex justify-between items-center p-4 rounded-lg bg-gray-50 dark:bg-gray-700">
                    <span className="text-gray-700 dark:text-gray-300">Original Amount:</span>
                    <span className="text-xl font-bold text-gray-900 dark:text-white">₹{result.originalAmount}</span>
                  </div>

                  <div className="flex justify-between items-center p-4 rounded-lg bg-green-50 dark:bg-green-900/20">
                    <span className="text-gray-700 dark:text-gray-300">GST Amount ({gstRate}%):</span>
                    <span className="text-xl font-bold text-green-600 dark:text-green-400">₹{result.gstAmount}</span>
                  </div>

                  <div className="flex justify-between items-center p-4 rounded-lg bg-gray-50 dark:bg-gray-700">
                    <span className="text-gray-700 dark:text-gray-300">CGST ({parseFloat(gstRate) / 2}%):</span>
                    <span className="text-lg font-semibold text-gray-900 dark:text-white">₹{result.cgst}</span>
                  </div>

                  <div className="flex justify-between items-center p-4 rounded-lg bg-gray-50 dark:bg-gray-700">
                    <span className="text-gray-700 dark:text-gray-300">SGST ({parseFloat(gstRate) / 2}%):</span>
                    <span className="text-lg font-semibold text-gray-900 dark:text-white">₹{result.sgst}</span>
                  </div>

                  <div className="flex justify-between items-center p-4 rounded-lg bg-gradient-to-r from-green-500 to-green-600">
                    <span className="text-white font-semibold">Total Amount:</span>
                    <span className="text-2xl font-bold text-white">₹{result.totalAmount}</span>
                  </div>

                  <div className="grid grid-cols-2 gap-3 mt-6">
                    <button
                      onClick={() => copyToClipboard(`Original: ₹${result.originalAmount}\nGST (${gstRate}%): ₹${result.gstAmount}\nTotal: ₹${result.totalAmount}`)}
                      className="px-4 py-2.5 rounded-lg bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300 font-medium transition-colors"
                    >
                      📋 Copy
                    </button>
                    <button
                      onClick={printResults}
                      className="px-4 py-2.5 rounded-lg bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300 font-medium transition-colors"
                    >
                      🖨️ Print
                    </button>
                  </div>
                </div>
              ) : (
                <div className="text-center py-12">
                  <div className="text-6xl mb-4">🧮</div>
                  <p className="text-gray-500 dark:text-gray-400">
                    Enter amount and click Calculate to see results
                  </p>
                </div>
              )}
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
