'use client';

import { useState, useEffect } from 'react';
import Link from 'next/link';
import Footer from '../../components/Footer';

export default function QRCodeGenerator() {
  const [text, setText] = useState('');
  const [qrType, setQrType] = useState<'text' | 'url' | 'email' | 'phone'>('text');
  const [qrSize, setQrSize] = useState(200);
  const [qrColor, setQrColor] = useState('#000000');
  const [bgColor, setBgColor] = useState('#ffffff');
  const [qrCodeUrl, setQrCodeUrl] = useState('');

  const generateQRCode = () => {
    if (!text) return;
    // Using QR Server API for QR code generation
    const encodedText = encodeURIComponent(text);
    const url = `https://api.qrserver.com/v1/create-qr-code/?size=${qrSize}x${qrSize}&data=${encodedText}&color=${qrColor.replace('#', '')}&bgcolor=${bgColor.replace('#', '')}`;
    setQrCodeUrl(url);
  };

  useEffect(() => {
    generateQRCode();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [text, qrSize, qrColor, bgColor]);

  const downloadQRCode = () => {
    if (qrCodeUrl) {
      const link = document.createElement('a');
      link.href = qrCodeUrl;
      link.download = `qrcode-${Date.now()}.png`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
    }
  };

  const copyQRCodeLink = () => {
    if (qrCodeUrl) {
      navigator.clipboard.writeText(qrCodeUrl);
      alert('QR Code URL copied to clipboard!');
    }
  };

  const shareQRCode = async () => {
    if (navigator.share && qrCodeUrl) {
      try {
        await navigator.share({
          title: 'QR Code',
          text: `QR Code for: ${text}`,
          url: qrCodeUrl,
        });
      } catch (err) {
        console.log('Error sharing:', err);
      }
    } else {
      alert('Sharing not supported on this browser');
    }
  };

  const saveToHistory = () => {
    const history = JSON.parse(localStorage.getItem('qr_history') || '[]');
    const newEntry = {
      text,
      type: qrType,
      timestamp: new Date().toISOString(),
      url: qrCodeUrl,
    };
    history.unshift(newEntry);
    localStorage.setItem('qr_history', JSON.stringify(history.slice(0, 10))); // Keep last 10
    alert('Saved to history!');
  };

  const printQRCode = () => {
    if (qrCodeUrl) {
      const printWindow = window.open('', '', 'height=600,width=600');
      if (printWindow) {
        printWindow.document.write(`
          <html>
            <head>
              <title>QR Code - InvoSync</title>
              <style>
                body { 
                  font-family: Arial, sans-serif; 
                  display: flex; 
                  flex-direction: column;
                  align-items: center; 
                  justify-content: center;
                  padding: 40px;
                  text-align: center;
                }
                h1 { color: #0891b2; margin-bottom: 20px; }
                img { margin: 20px 0; border: 2px solid #e5e7eb; padding: 20px; }
                .info { margin-top: 20px; color: #6b7280; }
              </style>
            </head>
            <body>
              <h1>QR Code</h1>
              <img src="${qrCodeUrl}" alt="QR Code" />
              <div class="info">
                <p><strong>Content:</strong> ${text}</p>
                <p><strong>Type:</strong> ${qrType}</p>
                <p><strong>Generated:</strong> ${new Date().toLocaleString()}</p>
                <p style="margin-top: 30px; font-size: 0.9em;">Generated by InvoSync</p>
              </div>
            </body>
          </html>
        `);
        printWindow.document.close();
        printWindow.print();
      }
    }
  };

  const getPlaceholder = () => {
    switch (qrType) {
      case 'url':
        return 'https://example.com';
      case 'email':
        return 'mailto:email@example.com';
      case 'phone':
        return 'tel:+1234567890';
      default:
        return 'Enter text here';
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-gray-100 dark:from-gray-900 dark:via-gray-800 dark:to-gray-900">
      <header className="sticky top-0 z-50 w-full border-b border-gray-200 bg-white/80 backdrop-blur-sm dark:border-gray-800 dark:bg-gray-900/80">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex h-16 items-center justify-between">
            <Link href="/" className="flex items-center gap-2">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-gradient-to-br from-blue-600 to-indigo-600">
                <span className="text-xl font-bold text-white">I</span>
              </div>
              <span className="text-xl font-bold text-gray-900 dark:text-white">InvoSync</span>
            </Link>
            <Link href="/tools" className="text-sm font-medium text-gray-700 hover:text-gray-900 dark:text-gray-300 dark:hover:text-white">
              ← Back to Tools
            </Link>
          </div>
        </div>
      </header>

      <section className="container mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <div className="mx-auto max-w-5xl">
          <div className="inline-flex h-20 w-20 items-center justify-center rounded-2xl bg-gradient-to-br from-cyan-500 to-cyan-600 text-4xl shadow-lg mb-6">
            📱
          </div>
          <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl dark:text-white mb-4">
            QR Code Generator
          </h1>
          <p className="text-xl text-gray-600 dark:text-gray-300 mb-8">
            Create QR codes for URLs, text, contact info, and more.
          </p>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Generator Form */}
            <div className="rounded-2xl bg-white p-8 shadow-lg dark:bg-gray-800">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6">Generate QR Code</h2>

              <div className="space-y-6">
                <div>
                  <label className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    QR Code Type
                  </label>
                  <div className="grid grid-cols-2 gap-3">
                    {(['text', 'url', 'email', 'phone'] as const).map((type) => (
                      <button
                        key={type}
                        onClick={() => setQrType(type)}
                        className={`px-4 py-2.5 rounded-lg font-medium capitalize transition-all ${
                          qrType === type
                            ? 'bg-gradient-to-r from-cyan-500 to-cyan-600 text-white shadow-lg'
                            : 'bg-gray-100 text-gray-700 hover:bg-gray-200 dark:bg-gray-700 dark:text-gray-300'
                        }`}
                      >
                        {type}
                      </button>
                    ))}
                  </div>
                </div>

                <div>
                  <label htmlFor="text" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Content
                  </label>
                  <textarea
                    id="text"
                    value={text}
                    onChange={(e) => setText(e.target.value)}
                    rows={4}
                    className="w-full rounded-lg border border-gray-300 bg-white px-4 py-3 text-gray-900 focus:border-cyan-500 focus:outline-none focus:ring-2 focus:ring-cyan-500/20 dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                    placeholder={getPlaceholder()}
                  />
                </div>

                <div>
                  <label htmlFor="size" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                    Size: {qrSize}x{qrSize}px
                  </label>
                  <input
                    type="range"
                    id="size"
                    min="100"
                    max="500"
                    step="50"
                    value={qrSize}
                    onChange={(e) => setQrSize(parseInt(e.target.value))}
                    className="w-full"
                  />
                </div>

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label htmlFor="qrColor" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      QR Color
                    </label>
                    <div className="flex gap-2">
                      <input
                        type="color"
                        id="qrColor"
                        value={qrColor}
                        onChange={(e) => setQrColor(e.target.value)}
                        className="h-10 w-16 rounded border border-gray-300 dark:border-gray-600"
                      />
                      <input
                        type="text"
                        value={qrColor}
                        onChange={(e) => setQrColor(e.target.value)}
                        className="flex-1 rounded-lg border border-gray-300 bg-white px-3 py-2 text-gray-900 focus:border-cyan-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                      />
                    </div>
                  </div>

                  <div>
                    <label htmlFor="bgColor" className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-2">
                      Background
                    </label>
                    <div className="flex gap-2">
                      <input
                        type="color"
                        id="bgColor"
                        value={bgColor}
                        onChange={(e) => setBgColor(e.target.value)}
                        className="h-10 w-16 rounded border border-gray-300 dark:border-gray-600"
                      />
                      <input
                        type="text"
                        value={bgColor}
                        onChange={(e) => setBgColor(e.target.value)}
                        className="flex-1 rounded-lg border border-gray-300 bg-white px-3 py-2 text-gray-900 focus:border-cyan-500 focus:outline-none dark:border-gray-600 dark:bg-gray-700 dark:text-white"
                      />
                    </div>
                  </div>
                </div>

                <div className="pt-4 border-t border-gray-200 dark:border-gray-700">
                  <h3 className="text-sm font-semibold text-gray-900 dark:text-white mb-3">Quick Examples:</h3>
                  <div className="space-y-2">
                    <button
                      onClick={() => setText('https://invosync.com')}
                      className="w-full text-left px-4 py-2 rounded-lg bg-gray-50 hover:bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 text-sm text-gray-700 dark:text-gray-300 transition-colors"
                    >
                      Website URL
                    </button>
                    <button
                      onClick={() => setText('mailto:contact@invosync.com')}
                      className="w-full text-left px-4 py-2 rounded-lg bg-gray-50 hover:bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 text-sm text-gray-700 dark:text-gray-300 transition-colors"
                    >
                      Email Address
                    </button>
                    <button
                      onClick={() => setText('tel:+1234567890')}
                      className="w-full text-left px-4 py-2 rounded-lg bg-gray-50 hover:bg-gray-100 dark:bg-gray-700 dark:hover:bg-gray-600 text-sm text-gray-700 dark:text-gray-300 transition-colors"
                    >
                      Phone Number
                    </button>
                  </div>
                </div>
              </div>
            </div>

            {/* QR Code Preview */}
            <div className="rounded-2xl bg-white p-8 shadow-lg dark:bg-gray-800">
              <h2 className="text-2xl font-bold text-gray-900 dark:text-white mb-6">Preview</h2>

              <div className="flex flex-col items-center justify-center">
                {qrCodeUrl && text ? (
                  <div className="space-y-6">
                    <div className="p-6 bg-gray-50 dark:bg-gray-700 rounded-xl">
                      <img
                        src={qrCodeUrl}
                        alt="QR Code"
                        className="mx-auto"
                        style={{ width: qrSize, height: qrSize }}
                      />
                    </div>

                    <div className="space-y-3">
                      <button
                        onClick={downloadQRCode}
                        className="w-full rounded-lg bg-gradient-to-r from-cyan-500 to-cyan-600 px-6 py-3 font-semibold text-white shadow-lg transition-all hover:from-cyan-600 hover:to-cyan-700"
                      >
                        💾 Download QR Code
                      </button>

                      <div className="grid grid-cols-2 gap-2">
                        <button
                          onClick={printQRCode}
                          className="px-4 py-2.5 rounded-lg bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300 font-medium transition-colors text-sm"
                        >
                          🖨️ Print
                        </button>
                        <button
                          onClick={saveToHistory}
                          className="px-4 py-2.5 rounded-lg bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300 font-medium transition-colors text-sm"
                        >
                          📌 Save
                        </button>
                      </div>

                      <div className="grid grid-cols-2 gap-2">
                        <button
                          onClick={copyQRCodeLink}
                          className="px-4 py-2.5 rounded-lg bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300 font-medium transition-colors text-sm"
                        >
                          📋 Copy Link
                        </button>
                        <button
                          onClick={shareQRCode}
                          className="px-4 py-2.5 rounded-lg bg-gray-100 hover:bg-gray-200 dark:bg-gray-700 dark:hover:bg-gray-600 text-gray-700 dark:text-gray-300 font-medium transition-colors text-sm"
                        >
                          🔗 Share
                        </button>
                      </div>
                    </div>

                    <div className="p-4 bg-blue-50 dark:bg-blue-900/20 rounded-lg">
                      <p className="text-sm text-blue-800 dark:text-blue-300">
                        <strong>Tip:</strong> Test your QR code with a mobile device before printing or sharing.
                      </p>
                    </div>
                  </div>
                ) : (
                  <div className="text-center py-12">
                    <div className="text-6xl mb-4">📱</div>
                    <p className="text-gray-500 dark:text-gray-400">
                      Enter content to generate QR code
                    </p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
